### ISSUE TITLE
Support configurable embedded sea-map instances

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#1]
The next step after 
https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/197

is to be able to configure some basic parameters of a sea-map instance when embedding a map in an iframe, without requiring installing anything specific in the server. At a minimum it would be all the params sepcified in [config.json](https://github.com/SolidarityEconomyAssociation/sea-map#configjson)

**Comment by ColmMassey** [comment]
"What we will have to do to make it smooth and nice looking is to produce a simple api that configures and generates a map dynamically. This result of that would be that they (dotcoop/ICA/whoever else) will need to reference the api with config arguments attached. e.g.
the src of the iframe would be
https://api.solidarityeconomy.coop/map?dataset=dotcoop&group=region"

**Comment by ColmMassey** [comment]
Can we also support multiple versions of the code base this way? Would we need differernt subdomains for each version like
https://api_v1_71449c1.solidarityeconomy.coop/map?dataset=dotcoop&group=region"

or could that be a variable

https://api.solidarityeconomy.coop/map?dataset=dotcoop&group=region&ver=1_71449c1"

**Comment by wu-lee** [comment]
I've pushed an implementation for this, lightly tested on a local copy of playground.

https://github.com/SolidarityEconomyAssociation/sea-map/commit/dfa44567f252761fd17a85dc791417879cdbcbad

This allows two ways of overriding the config.json:
- in the HTML, by defining the settings as attributes of the `#map-app` element
- in the URL, as query parameters

The first way, briefly, looks like this (you can set several parameters this way, I just show one):

    <div id="map-app" map-app:initial-bounds="40.712, -74.227,40.774, -74.125" ></div>

A config parameter name like `initialBounds` gets mapped to `map-app:initial-bounds`. i.e. There's a namespace prefix to make sure there can't be clashes with existing HTML attributes. And there capitalisation is changed to hyphenation. This steals an idea from AngularJS. The reason for it is that attribute case can't be accessed from javascript - they get downcased before javascript sees them. 

The other way involves URLs which look like this:

    http://playground.solidarityeconomy.coop?initialBounds=40.712,-74.227,40.774,-74.125

You'll need URL escaping where necessary (i.e. space -> '+', question mark to '%3B', etc. use the JS `encodeURIComponent` function). Again, multiple parameters can be supplied, delimited by ampersands or semi-colons.

This is parsed client-side in the Javascript, so no extra PHP or Apache scripts needed.

**Comment by wu-lee** [comment]
I've discovered a bug testing this, which I've recorded in #21

**Comment by ColmMassey** [comment]
Where can I review this version?

**Comment by wu-lee** [comment]
It's currently deployed here for general testing:

https://dev.playground.solidarityeconomy.coop/?initialBounds=40.712,-74.227,40.774,-74.125&htmlTitle=This+Is+A+Demo

**Comment by ColmMassey** [comment]
Nice. Have all the parameters documented [here](https://github.com/SolidarityEconomyAssociation/sea-map#configjson) been implemented?

**Comment by ColmMassey** [comment]
Can you provide examples of the other supported configurations working?

**Comment by wu-lee** [comment]
I shall add some documentation of the other parameters I've permitted to be configured this way.

I've just published a demo illustrating the use of two embedded maps in the same page. They both set the title and the initial location.

http://playground.solidarityeconomy.coop/index-embed.html

One is embedded using a `#map-app` ID `div` with parameters in the attributes (there can be only one of these, because IDs must be unique). This can set the title of the parent page.

The other is embedded in an `iframe` (there can be multiple of these). These can't set the `htmlTitle` of the parent page.
    
(I note that without a title element, the `htmlTitle` parameter doesn't work on the former case. I bug I think, will add an issue.)

**Comment by wu-lee** [comment]
Documentation of config values now added. `defaultNongeoLatLng` removed since the code doesn't seem to use it. Some values I'm a bit sketchy about the usage, in which case the documentation is likewise.

**Comment by ColmMassey** [comment]
> 'defaultNongeoLatLng` removed since the code doesn't seem to use it.
When an inititative doesn't have a resolvable address, its dialog bubble is placed in a default place, like the centre of Oxford. Not used on DotCoop map as we discard all initiatives with dodgy addresses. Only really makes sense for regional maps, @dtmakm27 can you check if it has been lost in recent changes.

**Comment by ColmMassey** [comment]
Closing now as feature has been implemented. Will add any bugs in new issues.

**Comment by dtmakm27** [comment]
I will make it an issue so I do not forget

**Comment by dtmakm27** [comment]
@ColmMassey implemented and works

**Comment by wu-lee** [comment]
> Nice. Have all the parameters documented [here](https://github.com/SolidarityEconomyAssociation/sea-map#configjson) been implemented?

Just to add: not *all* of them can be changed via URLs/attributes, as I don't think it makes sense for all the config settings.

Currently they can only be changed if they have a `setter` defined in the config schema [here][config_schema.js], i.e. are marked 'settable' in the documentation [here][CONFIG.md]

[config_schema.js]: https://github.com/SolidarityEconomyAssociation/sea-map/blob/master/www/map-app/app/model/config_schema.js
[CONFIG.md]: https://github.com/SolidarityEconomyAssociation/sea-map/blob/master/CONFIG.md
