### ISSUE TITLE
Deploy a dev build of Oxford & Newbridge maps

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#10]
Using latest version of sea-map code deply to dev.oxford.solidarityeconomy.coop and dev.newbridge.solidarityeconomy.coop

**Comment by dtmakm27** [comment]
Uploaded

**Comment by dtmakm27** [comment]
@ColmMassey

**Comment by ColmMassey** [comment]
Should this have all the code changes that the dev.dotcoop.solidarityeconomy.coop has? @dtmakm27

**Comment by ColmMassey** [comment]
As the zooming rules seem like the old ones.

**Comment by dtmakm27** [comment]
does

https://dev.newbridge.solidarityeconomy.coop/


look like it uses the new ones or the old ones?

**Comment by ColmMassey** [comment]
The behaviour that made me think that oxford.newbridge.solidarityeconomy.coop was not up to date, was that selecting the filter group title in the primary panel zooms differently then when selecting in the secondary panel.
In dev.newbridge.solidarityeconomy.coop the behaviour is the same, suggesting it is more up to date. I guess we need build #s displayed in the app somewhere.

**Comment by dtmakm27** [comment]
OK, perfect, dev.oxford is out of date, will update

**Comment by ColmMassey** [comment]
dev.newbridge.solidarityeconomy.coop seems to load Newbridge and Oxford, and for some reasons the directory doubles up the newbridge inititatves.

**Comment by dtmakm27** [comment]
should be updated and fixed
