### ISSUE TITLE
dropdowns for advanced search need to be scrollable on mobile

### ISSUE THREAD

**Issue by King-Mob** [SolidarityEconomyAssociation/sea-map#109]

**Comment by ColmMassey** [comment]
It is not just the dropdowns. We seem to have lost the abilite to scroll the panel.

**Comment by King-Mob** [comment]
@ColmMassey I have 2 options for you.

1. Turn off the search section scrolling independently from the panel. I can already do this, and this fixes the issue. 
2. Give the search section a fixed height if the screen is shorter than the drop-downs, and have that be scrollable also. I think this will take at least another hour or two to get working.

**Comment by ColmMassey** [comment]
1 is probably fine.

**Comment by ColmMassey** [comment]
Working now on Fairfone, but we seem to have lost the Clear Filter button.
