### ISSUE TITLE
Panel behaviour needs further configuration 

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#118]
We need to be able to specify in config file if the panel is open or minimised when the page is first opened. 

At the moment we can hide the Show Datasets panel. We need to extend that to hide any of the panels.

**Comment by ColmMassey** [comment]
Is this also the place to start supporting other configurations of the panels, lile the colour of the Teal tab button? @King-Mob

**Comment by King-Mob** [comment]
@ColmMassey I am assuming colour of the tab button is teal unless a suitable hex code is supplied in the config.

____________

I can get the sidebar to open when the page is first opened. 

What I'm grappling with at the moment is opening it into a state that looks good i.e. so the directory has a list of entries in it.

There are 2 ways this could happen. 

- The site could wait until after the map data has loaded to open the sidebar, which is when you can see an actual directory.
- The site could refresh the sidebar when the map has loaded.

This is based on the assumption that you want the sidebar to be in its most up to date state when it's open. If it's fine to just open it at the start, then that's great, I have that now.

**Comment by ColmMassey** [comment]
>     * The site could wait until after the map data has loaded to open the sidebar, which is when you can see an actual directory. (this is what I've gone with for the moment)

You mean the panel slides out only after the map and pins have appeared? That seems fine.

**Comment by ColmMassey** [comment]
Yes, teal as default. ICA colour is  #8E0B56

**Comment by ColmMassey** [comment]
Buglet: On phones in landscape when you have panel open on a co-op's details, you can't scroll if there is data offscreen. Not sure how recent this is.

**Comment by King-Mob** [comment]
@ColmMassey I'm having difficulty replicating this bug. On my phone and on the mobile options on the browser dev tools, I can scroll on the panel.

**Comment by ColmMassey** [comment]
I was testing multiple versions/bugs simultaneously. I can't replicate on dev.ica but only on dev.dotcoop and dotcoop, but they are both old versions, so we can ignore.

**Comment by ColmMassey** [comment]
I think the about box is hidden, by default. Needs to be there for ica

**Comment by King-Mob** [comment]
Sorry, was part of testing the config. Have pushed and deployed the fix.

**Comment by ColmMassey** [comment]
When you select a country from the directory lower down in the list the directory scrolls back up to the top.

**Comment by ColmMassey** [comment]
>When you select a country from the directory lower down in the list the directory scrolls back up to the top.

@wu-lee Can you take a peak at this bug and see if it's anything obvious?

**Comment by wu-lee** [comment]
I think the problem is that there's a mouse-click handler bound to the sidebar which sets the focus to the `dir-filter` element, but only if the width of the window is greater than a medium-large threshold (tablet sized?)

If I comment this line out, this problem seems to be resolved. I can't tell if it breaks some other functionality tho.  This line's vintage is February 2020, so it's not something added recently.

https://github.com/SolidarityEconomyAssociation/sea-map/blob/8690c352dc495202605194980e4790b49d709763/www/map-app/app/view/sidebar/directory.js#L55

**Comment by ColmMassey** [comment]
Can I try it out and I can check for any negative consequences?

**Comment by wu-lee** [comment]
Ok, I've deployed it on the dev server.

**Comment by ColmMassey** [comment]
> Ok, I've deployed it on the dev server.

That seems to work and doesn't seem to mess anything else up. Can you merge it with thelast of John's changes?

**Comment by wu-lee** [comment]
Ok, done, now on `dev`

**Comment by ColmMassey** [comment]
Hmmm. There are still differences. It may be just in config files. The tab colour is purple and the about box shouldn't be disabled. I wonder if there was a config version not commited.

**Comment by wu-lee** [comment]
I think I may not have pulled John's latest commits, so tried again and made sure I had them - the about page seems to be there now.

**Comment by ColmMassey** [comment]
Okay. Look right now. Have now shared with ICA for approval before pushing to prod.
