### ISSUE TITLE
sea-map directory colours are hardwired to the activity vocab

### ISSUE THREAD

**Issue by wu-lee** [SolidarityEconomyAssociation/sea-map#128]
they need to be configuarable - map pins also need to be configurably coloured (either by dataset, by category, or something else)

**Comment by ColmMassey** [comment]
Still seeing miscoloured markers from time to time.
![Untitled](https://user-images.githubusercontent.com/1162642/161145608-eb0284bc-6f5a-439d-bcd0-5f8beaae4e77.png)

**Comment by wu-lee** [comment]
This is achievable now, it just needs a specific example to be implemented to show it works.

**Comment by ColmMassey** [comment]
https://github.com/SolidarityEconomyAssociation/owned-by-oxford-project/issues/9#issuecomment-1170988410

**Comment by ColmMassey** [comment]
Let's test that this works in the KIITC project. https://github.com/DigitalCommons/KIITC/issues/1
