### ISSUE TITLE
Unlocalised phrases outstanding

### ISSUE THREAD

**Issue by wu-lee** [SolidarityEconomyAssociation/sea-map#134]
So far I've noticed these phrases are still not localised:
- [x] "Datasets" in the datasets panel
- [x] "Mixed Sources" in the datasets panel
- [x] The web page title

**Comment by ColmMassey** [comment]
Can these be added to the spreadsheet we use to get ICA to translate for us?

**Comment by King-Mob** [comment]
added to the spreadsheet

**Comment by wu-lee** [comment]
@King-Mob I should mention that there are some alterations to the phrases in the sea-map code I've made. Some additions and some removals. The code is not all pushed yet, pending a bit of reorganisation.

**Comment by King-Mob** [comment]
the loading message is also in english

**Comment by ColmMassey** [comment]
I have seen a loading message in Korean!

**Comment by ColmMassey** [comment]
The search panel in verion sea-map@1.2.3_7e545ea-dev when KO is selected has no drop down options.

**Comment by wu-lee** [comment]
I've added a mechinism to localilse the page titles in a commit on `dev`. To use:
- remove `htmlTitle` option in config, as this takes priority
- add a `<title>..</title>` element in the `<head>` section of the `about.html` file as an alternative default
- specialise this with extra sibling `<title lang="XX">...</title>` elements

I've not yet done this for the existing map sites, due to lack of time so far.
