### ISSUE TITLE
Dialog Bubble Tweaks

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#15]
Set the max size of the large dialog bubble to this
![image](https://user-images.githubusercontent.com/1162642/76707974-59503d80-66eb-11ea-945d-bfe6803e7004.png)

Hide all dialog bubbles when navigating through the search stack.

When hovering over an initiative's name in the directory or a list of search matches and that co-op is visible on the map, display the small dialog bubble for that co-op. Don't induce any panning or zooming

**Comment by dtmakm27** [comment]
Hide all dialog bubbles when navigating through the search stack

Could you clarify that. Which bubbles would that be

**Comment by ColmMassey** [comment]
Large dialog bubble = 
![large-bubble](https://user-images.githubusercontent.com/1162642/76711368-5400ec00-6707-11ea-9840-0340530b1089.png)
Small dialog bubble = 
![small-bubble](https://user-images.githubusercontent.com/1162642/76711373-5a8f6380-6707-11ea-9bf0-6d0ac82293e1.png)

But now that I think of it, only a large one could be open at a time and the small ones are now only used when hovering.

**Comment by dtmakm27** [comment]
When hovering over an initiative's name in the directory or a list of search matches and that co-op is visible on the map.

I have implemented that and it also checks if you are zoomed in enough on the map to see the marker (when it isn't clustered)

i.e. tooltip shows up only this way:
![Screenshot from 2020-03-22 21-55-40](https://user-images.githubusercontent.com/34026440/77261707-478d0e00-6c88-11ea-8be4-82049657888e.png)


instead of this..
![Screenshot from 2020-03-22 22-04-32](https://user-images.githubusercontent.com/34026440/77261805-2d076480-6c89-11ea-8dce-290391397e1d.png)

**Comment by dtmakm27** [comment]
implemented at https://dev.playground.solidarityeconomy.coop/?initialBounds=40.712,-74.227,40.774,-74.125&htmlTitle=This+Is+A+Demo

**Comment by ColmMassey** [comment]
> I have implemented that and it also checks if you are zoomed in enough on the map to see the marker (when it isn't clustered)

Did you need to do this because you can't display a tooltip with out expanding out the cluster? Can you see if you can somehow supress expanding the cluster when displaying the tool tip?

**Comment by dtmakm27** [comment]
> > I have implemented that and it also checks if you are zoomed in enough on the map to see the marker (when it isn't clustered)
> 
> Did you need to do this because you can't display a tooltip with out expanding out the cluster? Can you see if you can somehow supress expanding the cluster when displaying the tool tip?

No straightforward way of doing that I'm afraid.
I could try to uncluster one marker and show the tooltip for that one (and then put it back in the cluster when you remove the mouse pointer)

Should I spend more time on this issue?

**Comment by ColmMassey** [comment]
> Should I spend more time on this issue?

Not now. Happy to close this issue. I'll create a new ticket for that extra functionality for a later date.
