### ISSUE TITLE
Evaluate Collaborate for change data complexity

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#151]
Collaborate for Change https://www.cfctogether.org/

Look at their survey and identify any issues with us replicating the survey using our Limesurvey structures and our import scripts.

Evaluate if there is any reason why we couldn't create a Limesurvey/Loader/Mykomap instance for them in under a few hours. 

If not let them know we will create one for them shortly.

**Comment by ColmMassey** [comment]
I think only issue is that they don't have Activities but a much simpler set of Foci as their primary filter category.

Environment: the physical world in which we live and which sustains life on earth; CfC values mean that the environment must be protected and human activity limited by the natural resources and energy available.

Economy: the system we use to meet our needs through the production and consumption of goods and services; CfC values mean that the economy operates within ecological limits and with fair distribution.

Politics: the governing apparatus used in society to govern; CfC values mean that our governance becomes more participatory, inclusive, accountable, and co-operative, especially for minority and discriminated groups.

Community: the condition of sharing or having certain places, attitudes and interests in common; CfC values mean that communities of place and interest are nurturing and healthy; they are inclusive of all of us regardless of national identity, ethnicity, race, gender, disability or sexual orientation; they include urban and civic spaces, arts and culture, and sport.

Social: the interactions with the people in our family units and those outside those units which bind us together and help us meet our human and family needs for security and wellbeing; CfC values mean that we respect the different types of non-nuclear families that exist today, and non-traditional gender roles and sexual preferences; and we welcome progressive ideas that look to improve the whole raft of issues that impact us, our families and our wider social circles e.g. education, health, social security, housing, justice, etc.

**Comment by ColmMassey** [comment]
So we would need to be able to support this 'local vocabulary', which we cannot do right now, but will be able to support with @wu-lee's imminant changes for OBO. https://github.com/SolidarityEconomyAssociation/owned-by-oxford-project/issues/3

Can you confirm @wu-lee?

**Comment by wu-lee** [comment]
Hopefully so - I shall bear this requirement in mind whilst making these changes.

**Comment by ColmMassey** [comment]
> Hopefully so - I shall bear this requirement in mind whilst making these changes.

Trying to recall now, but wasn't there a limitation on what we could do with a local vocabulary with the current design? We would be able to load and display the data in dialogs but not use as options for the filters? Or was it that it could be used to define the catagories in the directory, but not the filters?

**Comment by ColmMassey** [comment]
> Trying to recall now, but wasn't there a limitation on what we could do with a local vocabulary with the current design? We would be able to load and display the data in dialogs but not use as options for the filters? Or was it that it could be used to define the catagories in the directory, but not the filters?

Wanted to get back to CfC today. @wu-lee, can you comment on my concern that the local vocabs couldn't be used in a filter?

**Comment by ColmMassey** [comment]
> so I'll have a look at this too and should be able to say with more certainty later, if you need that.

For the moment, it would be enough to know if they could be used in the Directory, if not in a filter.

**Comment by wu-lee** [comment]
I think it would be able to use it in the Directory.

**Comment by ColmMassey** [comment]
Okay, so let's create a map for CFC

https://github.com/SolidarityEconomyAssociation/sea-map/issues/153
