### ISSUE TITLE
Implement Info panel layout

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#17]
About
The .coop interactive map provides a visual database of all active .coop websites. All .coop domain registrants are verified to ensure that the cooperative is guided by the Cooperative Principles and the values that they promote. Cooperatives are the original ethical business!

DotCoop provides this directory at no charge for all active .coop domains. DotCoop is dedicated to helping people identify and locate co-ops on the Internet and next door.

You can search in your area easily or find a cooperative you know by name in the search box. Find co-ops near you that are dedicated to the cooperative principles and are "Proud to be .coop!"

Can’t find your favorite co-op? Check with them to see if they have a .coop website yet and if they don’t, let them know that you were looking for them on www.directory.coop!

This map and directory has been produced by the [Solidarity Economy Association](https://www.solidarityeconomy.coop/projects/dotcoop) for our partners DotCoop.  

Technical information about the technology behind this map and directory can be found [here](https://github.com/SolidarityEconomyAssociation/sea-map/wiki).

[Version number of sea-map code].

**Comment by dtmakm27** [comment]
@ColmMassey Has this been provided by any chance?

**Comment by ColmMassey** [comment]
He said he will provide it later tomorrow.

**Comment by dtmakm27** [comment]
Hi, any updates?

**Comment by ColmMassey** [comment]
Ok, the text from dotCoop is now in the top of this Issue.

**Comment by ColmMassey** [comment]
Sorry. There has been some back and forth re capitalisation. DotCoop (capital 'D' and 'C') is to be used when talking about the company and .coop (all lowercase) everywhere else. So we need to update the load screen text to lower case of COOP and &htmlTitle=.coop Map

**Comment by dtmakm27** [comment]
https://dotcoop.solidarityeconomy.coop/

Done, but I found a small bug in config_schema that was not loading the html. @wu-lee you might want to take a look. I made a hacky solution for now. search for the 'todo:' in config schema in the latest deployment

**Comment by dtmakm27** [comment]
we do not yet have the version (tag) number in the variables. This should happen when building the project. @wu-lee could you 'echo >' that in the versions.json file when running npm build?

**Comment by ColmMassey** [comment]
>we do not yet have the version (tag) number in the variables. 
Let's leave it for now. We can add in next iteration.

**Comment by wu-lee** [comment]
@dtmakm27 
> I found a small bug in config_schema

Ok, Can you point me at the right place to look, in a new issue?

> could you 'echo >' that in the versions.json file when running npm build?

Yes, likewise please create an issue, and I can add it to the queue.

**Comment by ColmMassey** [comment]
I think the only autogenerated part of this panel should be the version #(s).
The rest should be hand coded html tailored for this instance.
So we can close this once the version # is being added automatically.

**Comment by wu-lee** [comment]
> I found a small bug in config_schema that was not loading the html.

Just for the record, I believe I looked at this schema_config workaround some time ago and resolved it.

**Comment by ColmMassey** [comment]
> So we can close this once the version # is being added automatically.

How big a job is it to do this?

**Comment by ColmMassey** [comment]
Version # bit is covered here https://github.com/SolidarityEconomyAssociation/sea-map/issues/72

Closing this now, unless anyone thinks there is something outstanding re the schema-config bug
