### ISSUE TITLE
Change how directory groups co-ops 

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#2]
Through the config file it is possible to group initiatives in the directory either by Activity, Locality or Country. We need to extend this to support grouping using Organisation Type, Region and whether it has or does not have a companies house #.
Then make it possible to modify the choice through the sea-app interface.

**Comment by ColmMassey** [comment]
@wu-lee @dtmakm27 How easy is this to do?

**Comment by dtmakm27** [comment]
Hey @ColmMassey 

if I am understanding you correctly, you would like to:
1. Be able to group them by any data field in the Directory tab
2. Be able to change the grouping field in the interface

I could not quite understand: "whether it has or does not have a companies house #"

**Comment by ColmMassey** [comment]
I think this ticket needs to be split into 2 or more. Note it's not in this sprint.

**Comment by ColmMassey** [comment]
Closing as a duplicate to be replaced by 
https://github.com/SolidarityEconomyAssociation/sea-map/issues/52 &
https://github.com/SolidarityEconomyAssociation/sea-map/issues/53

Ignore reference to Companies House # @dtmakm27
