### ISSUE TITLE
initialBounds is not fully respected, it is reset when the data is loaded.

### ISSUE THREAD

**Issue by wu-lee** [SolidarityEconomyAssociation/sea-map#21]
When an `initialBounds` value is set in the config, or in the HTML attributes or URL, it works, intially. For example, testing on localhost (else replace the domain accordingly for playground or some other installation):

http://localhost:8080/?initialBounds=40.712,%20-74.227,40.774,%20-74.125

This initially shows a zoomed-in view of Newark.  But when the data is loaded, it zooms back to show the entire set of data points. This shouldn't happen.

**Comment by ColmMassey** [comment]
There are many events that trigger zoom to display all visible markers. I reckon there is one which kicks in after the directory is loaded. It would not be noticed if the starting zoom area is already zoomed beyond the visible markers.

**Comment by ColmMassey** [comment]
Might be easily addressed by @dtmakm27 when he's fixing the other zoom pan tweaks. @wu-lee

**Comment by dtmakm27** [comment]
fixed at https://dev.playground.solidarityeconomy.coop/?initialBounds=40.712,-74.227,40.774,-74.125&htmlTitle=This+Is+A+Demo
