### ISSUE TITLE
When an inititative doesn't have a resolvable address, its dialog bubble is placed in a default place, like the centre of Oxford. Not used on DotCoop map as we discard all initiatives with dodgy addresses. Only really makes sense for regional maps, @dtmakm27 can you check if it has been lost in recent changes.

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#24]

**Comment by ColmMassey** [comment]
Had it been removed? Where can I review?

**Comment by dtmakm27** [comment]
It has been added. I can show it on a mini-website that has initiatives without a geo location (and use the default one)
Do oxford or newbridge have any initiatives without a lat/lon

**Comment by ColmMassey** [comment]
Refill Oxford has no address at all.
https://data1.solidarityeconomy.coop/sea-lod/oxford/113.html

Note there are other places that just have partial postcodes.
https://data1.solidarityeconomy.coop/sea-lod/oxford/102.html

**Comment by ColmMassey** [comment]
I think this is all good now, but let's leave it open until a sprint where we are focusing on regional maps.
