### ISSUE TITLE
Implement caching for simple, single source sparql query

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#26]
See [here](https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/209)

Use .coop 'all data' query as example.

**Comment by dtmakm27** [comment]
implemented in latest commits at:
http://dev.playground.solidarityeconomy.coop/

we need to fix some issues with server permissions before we can make the cache to update itself routinely.
I suggest we handle that issue in the next sprint when handling the more complex issues with caching, and we just stress test the current servers

Thoughts?

**Comment by ColmMassey** [comment]
Seems fine to sort out auto updating of cache in next sprint. Made note in #25
