### ISSUE TITLE
Add "View map in fullscreen" in mini website

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#27]
When the miniwebsites are open in mobile mode, there is a button to open the sea-map in full screen mode. 

![View The Map](https://user-images.githubusercontent.com/1162642/77255162-632eef00-6c5d-11ea-9d6b-e9367a6f760c.png)

We need this option also when in large screen mode but with the text to _View the map in full screen_.

**Comment by dtmakm27** [comment]
@ColmMassey 
Would you prefer having a button that directs you to a 
https://newbridge.solidarityeconomy.coop/map.html

or an actual fullscreen btn like:
http://brunob.github.io/leaflet.fullscreen/

**Comment by ColmMassey** [comment]
Let's go with the first option.

**Comment by dtmakm27** [comment]
which one do you like more?  (text will be changed to View map in fullscreen)
![testview2](https://user-images.githubusercontent.com/34026440/79325170-a270f880-7f08-11ea-9c5c-4d5bd5550c68.png)
![testview1](https://user-images.githubusercontent.com/34026440/79325176-a3a22580-7f08-11ea-9263-b9fbbc1b5ef4.png)

**Comment by ColmMassey** [comment]
The second one. Use same green used on other button in Newbridge. Colour is fine for Oxford.

**Comment by dtmakm27** [comment]
added for both newbridge and oxford:
https://dev.oxford.solidarityeconomy.coop/
http://dev.newbridge.solidarityeconomy.coop/

**Comment by dtmakm27** [comment]
@ColmMassey

**Comment by ColmMassey** [comment]
:-)
