### ISSUE TITLE
Narrow screen panel behaviour

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#29]
When you start a fresh update of sea-app when working on a very narrow screen, showing and hiding the panel does not trigger anyn recentering, as it does on other screen ratios.

**Comment by ColmMassey** [comment]
Moving this into next sprint.

**Comment by dtmakm27** [comment]
HI so if i am getting this correctly
![image](https://user-images.githubusercontent.com/34026440/84569973-279a5180-ad82-11ea-9741-7190d015f0d7.png)

in really narrow screens it does not get recentered properly? i.e. in the image above the marker should be shown in the small patch of map as in the second picture: 

![image](https://user-images.githubusercontent.com/34026440/84570008-57495980-ad82-11ea-8cc4-e4a80aa2380e.png)

**Comment by ColmMassey** [comment]
It seems to work now for me on my phone at the moment! What ratios/browser are you evaluating?

**Comment by dtmakm27** [comment]
It seems to work on all ratios for me as well, that's why I got slightly confused
pictures are in 330x650

**Comment by ColmMassey** [comment]
I can't recreate, so let's close.
