### ISSUE TITLE
Change 'Zoom/Pan on select' rules to be more intuitive

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#3]
- [x] Selecting initiatives in the search results panel should behave the same as in the directory panel.
- [x] When you select an initiative marker always open the dialog.
- [x] When you selecting initiatives in a panel:
   - [x] the initiative marker should be centred in the visible part of the map.
   - [x] The ~~small~~ large dialog bubble showing just the name should be displayed.
   - [x] No auto-zooming should occur.
- [x] A failed search should not induce a zoom or pan.

**Comment by dtmakm27** [comment]
The small dialog bubble showing just the name should be displayed.

Hm, wouldn't it make more sense to open the full buble?

i.e. after a click you get: 
![Screenshot from 2020-03-12 21-18-09](https://user-images.githubusercontent.com/34026440/76567587-038b5380-64a7-11ea-8b05-3fce89e6393a.png)


rather than:

![Screenshot from 2020-03-12 21-19-55](https://user-images.githubusercontent.com/34026440/76567769-62e96380-64a7-11ea-9a8e-b5a817b72e33.png)



We can do either one but the opened one seems to have a better flow

**Comment by ColmMassey** [comment]
Leave the version you think works most smoothly. We can evaluate with all the other tweaks and see.

**Comment by dtmakm27** [comment]
This should be done in https://dev.playground.solidarityeconomy.coop/ @ColmMassey

**Comment by ColmMassey** [comment]
>Selecting initiatives in the search results panel should behave the same as in the directory panel.
When you select an initiative from the search panel, the dialog box is centred. When you select from a directory panel, the marker is centred. It needs to be the marker.

**Comment by ColmMassey** [comment]
Failed searches regularly produce zooming/panning.

**Comment by dtmakm27** [comment]
When you select an initiative from the search panel, the dialog box is centred. When you select from a directory panel, the marker is centred. It needs to be the marker.
Good catch! Now it's fixed, will upload later when i fix the search issue as well

**Comment by dtmakm27** [comment]
Failed searches regularly produce zooming/panning.

What do you mean by failed search?

Context: After you have filtered results based on a successful search, removing the search filter causes a zoom and pan
When a failed search happens it will remove the previous search filter which causes the zoom and pan and it will not apply a new one

Could you give me the sequence of events that trigger the panning and zooming we don't want?

e.g. searching for "asd" will get results and zoom/pan then searching for "asdfg" will show all and zoom/pan back to all the results

**Comment by ColmMassey** [comment]
> e.g. searching for "asd" will get results and zoom/pan then searching for "asdfg" will show all and zoom/pan back to all the results

Yes, this is what I meant by "Failed searches regularly produce zooming/panning."

Desired behaviour: If a search does not produce any results, all markers disappear but no zoom or pan should take place.

**Comment by dtmakm27** [comment]
Just to make it clear: on a failed Search you'd like for everything to disappear?

**Comment by ColmMassey** [comment]
I think so, as you didn't find anything?

**Comment by dtmakm27** [comment]
both should be fixed in https://dev.playground.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
Nice
