### ISSUE TITLE
Create ICA Youth Network instance of sea-map

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#30]
Using the data published [here](https://github.com/SolidarityEconomyAssociation/open-data/issues/11) create a sea-map instance at dev.ica-youth-network.solidarityeconomy.coop.

See https://github.com/SolidarityEconomyAssociation/open-data/issues/1 for background.

**Comment by wu-lee** [comment]
Ok, I've added a subdomain for this in the SEA zone file:
- `dev.ica-youth-network.solidarityeconomy.coop` -> `dev-0`
- `ica-youth-network.solidarityeconomy.coop` -> `sea-0`

No SSL certs as yet. That requires updating and redeploying the ansible scripts.

However, if you click through the SSL cert warnings you should now be able to view content when it is uploaded to `/var/www/vhosts/ica-youth-network.solidarityeconomy.coop/www/` on `dev-0` (courtesy of the dynamic virtual-host configuration which doesn't need to be told when new virtual hosts are added).

`sea-map` is more of a hassle, it needs a new Apache config for the virtual host, and manual re-issuing of the certs with `certbot`.

**Comment by wu-lee** [comment]
Ok, added this domain to the Ansible config and re-run it. SSL cert and a placeholder `index.html` are now in place. Ready for deployment of a sea-map site.

http://dev.ica-youth-network.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
Just 'assigned' this to you as you moved it to In Progress, reassign if I've gotten that wrong. I think all Issues in In Progress should be assigned to the folks working on it. Similarly All Issues in For Review should be assigned to the reviewer.

**Comment by dtmakm27** [comment]
Thanks Nick.
Map is deployed at: https://dev.ica-youth-network.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
:-)
