### ISSUE TITLE
Autopanning back to selected markers not appropriate.

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#31]
If you have a co-op selected and the full dialog is visible for the co-op (desktop mode) and you manually pan away from that part of the map so that the dialog is no longer visible and you change zoom depth, the map auto pans to pull the dialog back into view. This should not happen.

**Comment by dtmakm27** [comment]
fixed

http://dev.oxford.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
That works.
