### ISSUE TITLE
Check if co-ops are visible before calling auto zoom.

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#32]
If a co-op selection is already visible on a map when a zoom/pan to selection call is made, don't change the zoom depth, just pan to better centre them.
E.g. When we a search returns one or more successful matches.

Also can we reduce how much the map zooms out when it needs to pan or zoom to include the new selection. If only one match is found, should it change the zoom settings at all?

**Comment by dtmakm27** [comment]
I am not sure what"if a co-op selection is already visible on a map" would mean in technical terms for a cluster of coops 

and do we actually want this for multiple initiatives? i.e.
There are two ways of showing France

![Screenshot from 2020-04-07 01-24-44](https://user-images.githubusercontent.com/34026440/78617247-b5335f80-786e-11ea-8b4e-30e461ec75fa.png)
![Screenshot from 2020-04-07 01-24-55](https://user-images.githubusercontent.com/34026440/78617298-d6944b80-786e-11ea-9bb1-a6409e431a2b.png)

The bottom one is what currently happens, the top one is what I assume you are purposing to do. Is that correct?

**Comment by ColmMassey** [comment]
I see 3 cases:

- Only one marker in selection set: In this case you should only pan to centre the item.
- Multiple individual markers, no clusters: Attempt to pan in order include all in the map without zooming and only zoom out if that is not possible.
- Set includes clustres: Continue with current behaviour.

**Comment by ColmMassey** [comment]
Let's do a review of cluster management when you have finished this Issue.

**Comment by dtmakm27** [comment]
done at the latest map @ColmMassey 
https://dev.ica.solidarityeconomy.coop/

Could tweak it relatively easily if it does not behave as expected.
