### ISSUE TITLE
initial bounds are not calculated right when no initial bounds are supplied

### ISSUE THREAD

**Issue by dtmakm27** [SolidarityEconomyAssociation/sea-map#33]
dev.newbridge.solidarityeconomy.coop
There is an issue with calculating the bounds at start for both datasets (you can see they are zoomed out quite far away).

**Comment by ColmMassey** [comment]
Might be worth looking at these at the same time?
#32 & #31

**Comment by dtmakm27** [comment]
Fixed 
http://dev.oxford.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
> Fixed

So what is the default behaviour when no initial bounds are set?

**Comment by dtmakm27** [comment]
Ah, it is supposed to calculate it itself by using the lat/lng positions of every initiative

**Comment by ColmMassey** [comment]
> Ah, it is supposed to calculate it itself by using the lat/lng positions of every initiative
Is that what you are observing?

**Comment by dtmakm27** [comment]
Yes. Now it works. 

It didn't because of a bug which was setting lat/lng to 0 instead of undefined and taking in the 0 in the calculation. Now it's fixed

**Comment by ColmMassey** [comment]
Let me know what map I can evaluate it on.

**Comment by ColmMassey** [comment]
Currently not working on 

https://dev.oxford.solidarityeconomy.coop/map.html

**Comment by ColmMassey** [comment]
I think this fix has not been published yet.

**Comment by dtmakm27** [comment]
there was again a small bug in the config_schema that was not being shown locally. I patched it but Nick should probably take a closer look. Now it should be fine and working at: https://dev.oxford.solidarityeconomy.coop/map.html

@wu-lee i'll make a ticket describing it so you can give it a look

**Comment by dtmakm27** [comment]
should be fixed
