### ISSUE TITLE
config_schema bugs

### ISSUE THREAD

**Issue by dtmakm27** [SolidarityEconomyAssociation/sea-map#37]
In config schema line 95 - 110 each variable is being initialised by it's assigned init function. 
For some variables this seems to not quite work as expected. 
The two that I have come across are defaultLatLng which needs it's init() to be called once before it loads the passed values (in a config file, have not tested it for a url param)
and aboutHtml which did not initialise the about.html file as a string and just returned undefined. (hence you see the if statement that just directly assigns the already read html file). 
@wu-lee  any ideas?

    // Initialise the config value
    if (def.init) {
      //TODO: FIX THese BUGs
      
      if(def.id == "defaultLatLng")
        def.init()
      
      if(def.id == "aboutHtml")
        data[def.id] = about_html;
      else
        data[def.id] = def.init();

**Comment by ColmMassey** [comment]
See also https://github.com/SolidarityEconomyAssociation/sea-map/issues/36

**Comment by ColmMassey** [comment]
Test doesDirectoryHaveColours & disableClusteringAtZoom as well before closing this bug.

**Comment by wu-lee** [comment]
I believe #43 is now fixed. Can't find an issue matching 'colours', do you have a reference @ColmMassey ?

**Comment by wu-lee** [comment]
@dtmakm27 will have a look. Some of these init functions expect to get their data from the parameters passed via the `configSchema` constructor function [here in config_schema.js][1]

[1]: https://github.com/SolidarityEconomyAssociation/sea-map/blob/master/www/map-app/app/model/config_schema.js#L113-L131

I suspect these might be unset, but will need to test. Do you know an easy way to make the problem manifest itself?

**Comment by wu-lee** [comment]
I think I can fix the missing case of `aboutHtml`. Can't replicate the missing case of `defaultLatLng` tho? Seems to behave properly.

Test case pushed on `issue/37/config-schema` branch
