### ISSUE TITLE
Create option to set min/max zoom levels

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#38]
Create option to set min/max zoom levels when auto zoom/paning to include all of a directory subset on the map. 

Add to config.md documentation an explaination of the zoom levels.

**Comment by dtmakm27** [comment]
@ColmMassey 
added config options. They work as follows: 

maxZoomOnGroup - The maximum zoom in that can happen when selecting any particular group in directory, if 0 does no zooming. Defaults to 18 and auto decides best max zoom
maxZoomOnSearch - The maximum zoom in that can happen when searching any particular group, if 0 does no zooming. Defaults to 18 and auto decides best max zoom
maxZoomOnOne - The maximum zoom in that can happen when selecting an initiative, if 0 does no zooming. Defaults to 18 and auto decides best max zoom

https://dev.oxford.solidarityeconomy.coop/
http://dev.newbridge.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
This doesn't work as I would expect. Might need a demo.

**Comment by dtmakm27** [comment]
If it's because it doesn't work on Oxford, i fixed that, it should be doing as it is suggesting in the description
e.g. setting this:  https://dev.newbridge.solidarityeconomy.coop/?maxZoomOnSearch=4
should give a big zoom out 
(note: bigger number bigger zoom in; smaller number bigger zoom out)

**Comment by ColmMassey** [comment]
>https://dev.newbridge.solidarityeconomy.coop/?maxZoomOnSearch=4
So the url parameters are passed through to the iframe?

**Comment by dtmakm27** [comment]
https://dev.oxford.solidarityeconomy.coop/?maxZoomOnSearch=4

they can be passed or set in the config.json file in the mini-website
