### ISSUE TITLE
Make Search History state clearer

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#4]
There are a few tweaks we could do to make the search history navgation easier.
When you do a search across only within a filter group, that should be noted in the search history panel. 

![All-apple](https://user-images.githubusercontent.com/1162642/75569231-a5915180-5a4c-11ea-8668-2daaf9a91985.png)

![Italy-apple](https://user-images.githubusercontent.com/1162642/75569434-facd6300-5a4c-11ea-9a84-4920c862de55.png)

Secondly, when moving through the search stack, the search string window should update with the search used for that search.

**Comment by dtmakm27** [comment]
This should be done in https://dev.playground.solidarityeconomy.coop/ @ColmMassey

**Comment by ColmMassey** [comment]
>Secondly, when moving through the search stack, the search string window should update with the search used for that search.
This doesn't seem to have been done.

**Comment by dtmakm27** [comment]
Hm, Could you send a picture of what you mean

Are we talking about this text:
![Screenshot from 2020-03-14 21-37-59](https://user-images.githubusercontent.com/34026440/76690817-24d17880-663c-11ea-9b56-d2bedfa1fe8a.png)

Because that one seems to be changing and working for me.
tx

**Comment by ColmMassey** [comment]
No, this one...

![search](https://user-images.githubusercontent.com/1162642/76700900-00b17e00-66b4-11ea-9085-a79d9e8b0e0f.png)

**Comment by dtmakm27** [comment]
haha, my bad, thought it was the other one.

done in https://dev.playground.solidarityeconomy.coop/
