### ISSUE TITLE
Clustering gets locked somehow.

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#42]
In Oxford map (Windows - Firefox) when opening and closing small clusters, like the 2 initiatives at the South Oxford Community Centre, the cluster is green and displaying a 2, but you can still see the 2 spider legs and clicking no longer opens the cluster.

![ClustreBug](https://user-images.githubusercontent.com/1162642/79797511-49152900-834f-11ea-8c19-0265ae72a9cf.png)

**Comment by ColmMassey** [comment]
![Untitled](https://user-images.githubusercontent.com/1162642/84512375-c90c9f00-acbf-11ea-8a59-323be4ac60d6.png)

On Chrome on Windows 10

**Comment by ColmMassey** [comment]
I have a live locked cluster. Is there are debug info I can gather to assist debugging this?

**Comment by dtmakm27** [comment]
No need for now, it is really easily replicable and seems to be a constant problem
THX will get back with fixes :)

**Comment by dtmakm27** [comment]
Hey @ColmMassey 

Does it actually make sense for spiderifying to happen when zooming out in the first place?

![image](https://user-images.githubusercontent.com/34026440/84590977-ba92c480-ae32-11ea-80cd-b49080640b81.png)

Should we not just deselect the marker when the user zooms out? Basically what's currently going on is that when a marker is selected, we force it to spiderify when zooming in or out.
What I am suggesting is that we only spiderify when the user is zoomed in

Spiderifying like shown below, doesn't give the user any information (it even looks slightly confusing) and is a bit unsightly:

![image](https://user-images.githubusercontent.com/34026440/84591057-56243500-ae33-11ea-845a-bf225aa3c7ca.png)

I am suggesting that we make the handling in a similar way to this: https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

When clicking on a set of initiatives:
![image](https://user-images.githubusercontent.com/34026440/84591161-26c1f800-ae34-11ea-8dbe-338c49157911.png)

After zooming out: 
![image](https://user-images.githubusercontent.com/34026440/84591174-40fbd600-ae34-11ea-91ab-f858cb051ba5.png)



What are your thoughts?

**Comment by ColmMassey** [comment]
That sound sensible. Happy to give it a test drive.

**Comment by ColmMassey** [comment]
>I am suggesting that we make the handling in a similar way to this: https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

I do like this style. I agree there is no value in keeping the spider when you zoom out.

**Comment by dtmakm27** [comment]
implemented alongside the tile/marker fix. in the latest ica map: 
http://dev.ica.solidarityeconomy.coop/

The code is in a working condition and has been tested, but it could/should be written cleaner/with a bit more comments

There is an non-deterministic issue on mobile where the clusters do not open from time to time. This is more to do with leaflet's handling of 'touch' events rather than the code itself. I will see if i can fix it by fixing this issue: https://github.com/SolidarityEconomyAssociation/sea-map/issues/32

Could potentially be gone for the most part after #32 gets fixed.

I also have a proposal on the map functionality (that will fix this problem) which we can implement whenever it is deemed sufficient.

**Comment by ColmMassey** [comment]
I am not seeing the clustering getting locked anymore, even on mobile, but I am still seeing the spider's skeleton left visible on both mobile and desktop and combined with this comment

"The code is in a working condition and has been tested, but it could/should be written cleaner/with a bit more comments"

suggests that there is perhaps a refactor required of the cluster management code. 

I am closing this, and let's review this issue after you have finished #32.
