### ISSUE TITLE
Create Wordpress Theme to replace mini-websites.

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#49]

**Comment by ColmMassey** [comment]
And let's use the Newbridge project to test it.

**Comment by ColmMassey** [comment]
Email from Joe 
"I've put the theme up on this server: https://sea.zapdev.co.uk/

Would you/Newbridge be able to have a look to check whether it's suitable for requirements?

To access the backend, visit https://sea.zapdev.co.uk/wp-admin/

Some things to note:

I wasn't able to add color/font customization into it without spending at least another couple of days on it.

There are three custom options pages (accessible from the Options menu item in the sidebar). One for the header, one with general site options and one for the footer.

In the header options you can add a logo that will be used in place of the site name.

In the site options there is a field to change the name of case studies to something else and an option to add a font-awesome kit identifier (for adding icons in the footer options).

In the footer options there are fields for adding footer text, contact details and social links.

The site name and tagline can be changed in the General Settings section (accessible from the Settings menu item in the sidebar). In the Reading Settings you can change the default home page for the site.

Case studies are added in the Case Studies menu. There's one example in there.

I've tried to keep the theme as flexible as possible by letting the user decide what's added through the wordpress interface (called blocks). It's not altogether obvious how to use it until you're shown so if you or NB haven't used WordPress before then let me know and let's arrange a time to do that.

**Comment by ColmMassey** [comment]
This is great. 
I find wordpress quite mysterious sometimes, so please forgive any naive questions.

> There are three custom options pages (accessible from the Options menu item in the sidebar). 
> One for the header, one with general site options and one for the footer.
So these and the case study pages are currenlty the only editable options specific to this new theme?

Where would be the right place to set the map parameters?
https://github.com/SolidarityEconomyAssociation/sea-map/blob/master/CONFIG.md

>I've tried to keep the theme as flexible as possible by letting the user decide what's added through the wordpress interface (called blocks). 

So would this be how we would add the panel of text normally sitting to the left of the sea-map?

Where would we edit the characteristics of the sea-map frame? Can we allow it's size to be edited?

**Comment by ColmMassey** [comment]
https://github.com/joebillings/sea-wordpress-theme/ is where the Theme currenlty resides.

**Comment by ColmMassey** [comment]
This is being handed over to CodeOps. Which of you @wu-lee or @dtmakm27 shall I assign this to?

**Comment by wu-lee** [comment]
So far as I know we're both equally incompetent when it comes to wordpress plug-ins. :)  But perhaps Dean will correct me on that.

**Comment by ColmMassey** [comment]
You can arm wrestle over it!

**Comment by wu-lee** [comment]
Ok, I've forked @joebillings repo into the SEA github account, here:

https://github.com/SolidarityEconomyAssociation/sea-wordpress-theme

Not sure what else to do - we don't have any Wordpress instances to install it on... or do we?

Is there anything else outstanding to do?

**Comment by ColmMassey** [comment]
I guess that warrants a new Issue. Can you create a ticket to install a wordpress instance on the dev server at dev.wptest.etc, say and to use the template?

**Comment by dtmakm27** [comment]
> we're both equally incompetent when it comes to wordpress plug-ins.


:) indeed we are; you take the lead on this, but let's cowork on it so we both know what's going on

**Comment by wu-lee** [comment]
New issue here: https://github.com/SolidarityEconomyAssociation/sea-wordpress-theme/issues/1

I think this one can be closed?
