### ISSUE TITLE
Dialogs close too quickly when selecting marker at location with multiple markers.

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#5]
Try agile.coop. It shares a location with Domains. Select it and its dialog flashes up for a second, and then it closes and the green circle returns.

**Comment by ColmMassey** [comment]
Can you see this @dtmakm27? It seems to occur for every location with multiple initiatives.

**Comment by dtmakm27** [comment]
This should be done in https://dev.playground.solidarityeconomy.coop/ @ColmMassey
