### ISSUE TITLE
Resolve known issues with iframe

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#50]
We need to continue supporting iframe referencing of instances of sea-maps.
We need to identify the current weaknesses with how it currently works and address as well as we can.

**Comment by ColmMassey** [comment]
See https://github.com/SolidarityEconomyAssociation/dotcoop-project/issues/5

**Comment by ColmMassey** [comment]
"I have noticed that when I use the directory in Chrome (and possibly other browsers) when you try and click on the link below (for any of the domains) then it will not load.  I have traced this issue down and it is because the link is trying to load an HTTP site in an iFrame that was created from an HTTPS connection (e.g. that of the identity.coop site). IMHO the easiest way to resolve this is to add a ‘target=”_blank”’ attribute to the link so that the site is actually loaded in a brand new window.  @Colm SEA would need to action this should you decide that this is what is needed."

**Comment by dtmakm27** [comment]
> "I have noticed that when I use the directory in Chrome (and possibly other browsers) when you try and click on the link below (for any of the domains) then it will not load. I have traced this issue down and it is because the link is trying to load an HTTP site in an iFrame that was created from an HTTPS connection (e.g. that of the identity.coop site). IMHO the easiest way to resolve this is to add a ‘target=”_blank”’ attribute to the link so that the site is actually loaded in a brand new window. @colm SEA would need to action this should you decide that this is what is needed."

BTW @ColmMassey this was fixed the day they mentioned it :) (just making sure you're aware)
