### ISSUE TITLE
Add the graph of non self identified Newbridge inititatives to the Newbridge sea-map

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#51]
This issue covers the publication of the data.
https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/217

Need to think how to differentiate the differents sets' icons.

We probably don't need to worry about duplicates, as Newbridge will remove entries once they see an inititaltve has filled in the Limesurvey.

**Comment by wu-lee** [comment]
Sketchy about what this is asking for. Can you clarify what you mean by "non self identified", and what is needed wrt. icons @ColmMassey ?

**Comment by ColmMassey** [comment]
More details in the duplicate ticket here https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/217

**Comment by wu-lee** [comment]
So get the data from the Google sheet somehow. But also:

- Include these in Newbridge data exactly as the ones from Lime Survey?
- Show these on the map exactly as the ones from Lime Survey?

As noted in the other ticket you reference, there is a download URL, but this has no ETAG info, so it isn't possible to tell when the data is changed.  Which means polling, presumably every ten minutes as this is currently not adjustable independent of the data set. It's possible this may trigger some sort of Google anti-bot block.

**Comment by ColmMassey** [comment]
> * Include these in Newbridge data exactly as the ones from Lime Survey?
> 
> * Show these on the map exactly as the ones from Lime Survey?

No. It needs to be an independent graph. The Newbridge map would then include both data sets as independent graphs. No need for sameas handling.

**Comment by ColmMassey** [comment]
>It's possible this may trigger some sort of Google anti-bot block.

Hmm. If we can't find a way of checking if it has changed, I assume we have no option but to risk this.

**Comment by wu-lee** [comment]
See https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/217 for the grisly details, but I think this issue is referring to the Deep Adaptation data, and I believe adding it to Newbridge is now done (bar the bugs with the side-bar, which are separate issues).

**Comment by ColmMassey** [comment]
Tested changing something in google sheet and seeing it ripple all the way through. :-)
