### ISSUE TITLE
Context should be in text box when selecting search

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#56]
When you select the search tab in the side panel, the context should go to the text box by default.

**Comment by dtmakm27** [comment]
Could you clarify this?

**Comment by ColmMassey** [comment]
When the directory is open and you click on the Show search icon you need to explicitely select the text box before you can type a search term. The text cursor should be there automatically and you should be able to type straight away.

**Comment by dtmakm27** [comment]
@ColmMassey  Could you give it a try at: https://dev.ica.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
Bingo!
