### ISSUE TITLE
Visual clues needed for initiatives with no valid geo location

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#64]
When an initiative has no geo location for whatever reason, it doesn't get a visible icon, (although it seems to have an invisible one which is used by the zom and pan algorithm!)
But this Issue is more about making it clear when a co-op is present in the directory but will not have an icon.
I suggest that there should be a slight shading difference( little greyer) in the directory view and the text of the name of the co-op shpuld be in italics in both the regular directory, and if it appears in a search.

**Comment by ColmMassey** [comment]
In the dialog if there is some address text there make it also in italics with the text NO LOCATION AVAILABLE below the last line of any address present.

**Comment by dtmakm27** [comment]
Done here: https://dev.ica.solidarityeconomy.coop/
@ColmMassey
