### ISSUE TITLE
OrgType Search options not working

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#65]
In sea-map https://dev.ica.solidarityeconomy.coop/?searchedFields=orgStructure

All searched fail

**Comment by ColmMassey** [comment]
Should Qualifiers be searchable? Not documented as being searchabele.

**Comment by ColmMassey** [comment]
I think the search is working on the Label/Term Name? A weakness of using non human readable Labels. Can we also search across the Term's Definitions as well as label. Is there a way of easily setting the search option to search artoss all supported fields?

**Comment by dtmakm27** [comment]
fixed it in the latest map @ColmMassey 

https://dev.ica.solidarityeconomy.coop/?searchedFields=orgStructure
