### ISSUE TITLE
Markers are disappearing again. 

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#68]
In the latest build for .coop, I am seeing markers not appearing when selected in the directory. Zooming a level and they appear. Has there been a code regression of some sort @dtmakm27?

**Comment by ColmMassey** [comment]
I am seeing this in my current instance on Windows Firefox here https://identity.coop/directory/.

Look at Brazil in directory and start selecting co-ops. Problem appears quickly. However no porblems on Chrome and in an anonymous version of Firefox? So it has either just been fixed by a submission, or something subtler? What if caches were refreshing some but not all code/resources and this half way out of sync version is broken.

Error messages below appear for both working and non working maps.

![Untitled](https://user-images.githubusercontent.com/1162642/89167218-06303780-d573-11ea-91ed-23fdccdb4f8d.png)

**Comment by ColmMassey** [comment]
Just tried clearing the cache for identity.coop and behaviour is now back to normal!

**Comment by dtmakm27** [comment]
The log your showing is for the browser specifically (not the website) I think.

> Just tried clearing the cache for identity.coop and behaviour is now back to normal!

Dotcoop production map was updated with the latest map-app about 3-4 days ago, so it is definitely a caching error (i.e. you're using the code with the error rather than the latest code)

Shall we open a ticket for forcing cache refreshes on sea-map updates?

**Comment by ColmMassey** [comment]
> Shall we open a ticket for forcing cache refreshes on sea-map updates? @ColmMassey

Yes please. Then referece back to this ticket and close it.

**Comment by dtmakm27** [comment]
Hi, made one here https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/230 @ColmMassey
