### ISSUE TITLE
Second searches not clearing results of first search 

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#69]
After searching for a co-op, if you attempt another search, the old results are not cleared.

**Comment by dtmakm27** [comment]
Hi, this seems to happen randomly, spent some time testing it 
@ColmMassey where does it happen for you? 

for me it happens after i search ica then somal only and nowhere else (searched for 30 minutes)

**Comment by ColmMassey** [comment]
I am struggling to repeat this now. Couldn't replicate in firfox after 10 mins. Swithced to Chrome on dev.ica.. and quickly got 
![image](https://user-images.githubusercontent.com/1162642/89736025-769cf400-da5e-11ea-9d8d-8311cec78b0c.png)

**Comment by ColmMassey** [comment]
Okay this is repeatable on Chrome, firefox & Edge.  Search for cass and then case.

**Comment by dtmakm27** [comment]
@ColmMassey Fixed this

Was a really well hidden bug where the map was accessing information for hidden initiatives!  (i.e. cass -> no results, hides everything, while everything is hidden you search for case and try to access information about an initiative that is hidden (which you can't do on leaflet leaflet) and then reveal it)

Fixed the order to make sure they're revealed before being accessed.

updated ica and dotcoop:
example: http://dev.ica.solidarityeconomy.coop/
