### ISSUE TITLE
Add version # to info panel

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#72]
This issue started in https://github.com/SolidarityEconomyAssociation/sea-map/issues/17

The info panel needs a bespoke and an autogenerated part.

This ticket just covers the autogeneration of a version # for the sea-map build, that will appear at the bottom of the info panel.

**Comment by wu-lee** [comment]
Currently there's effectively a version in the deployed site, visible at `https://<sea-site>/configuration/version.json`. This is actually a git commit ID, so pinpoints the deployed code even more precisely than the version does - but it is less intelligible to mere mortals, and only indirectly tells you what version of `sea-map` was used (it's a commit ID in the sea site project which consumes the `sea-map` library; although the sea-map version should be discoverable from the versions/commit IDs in the site's `package-lock.json`, so long as that's been committed corrrectly, see comment below).

Is this isn't sufficient, the simplest thing would be to add another attribute to `version.json` using a version obtained either from the `sea-map` `package.json` or somewhere equivalent.

Note, we also have a problem keeping the sea-map `package.json`/`package-lock.json` versions in sync with the git tags denoting the versions in the repository. Fixing this requires clarifying, and perhaps automating the process of releasing `sea-map`.

A final aside: the lined data deployment now also has a commit ID included in the deployment. Visible at https://<data site>/<URI-PATH>/meta.json`. For example:

https://dev.data.solidarityeconomy.coop/sea-lod/oxford/meta.json

This is only deployed on Rubified open-data deployments - so not Co-ops UK, in particular.

**Comment by dtmakm27** [comment]
check key for version used in sea map config

**Comment by dtmakm27** [comment]
"version"

**Comment by wu-lee** [comment]
This addition, which writes the version field, is committed now.  It takes the version from sea-map's `package.json` file, but also adds the 'resolved' version, which has a commit ID (version alone is a bit vague, it indicates the code is from an arbitrary sequence of commits, so less useful for debugging).

@dtmakm27 - I don't think the pop-up code you wrote with the seaMapVersion alteration is committed yet? So it won't be visible in the pop-up.

**Comment by dtmakm27** [comment]
Added 
@wu-lee 
Could you test and confirm that it is getting the correct sea-map versions? 
https://dev.ica.solidarityeconomy.coop/

**Comment by wu-lee** [comment]
It's getting a version but I don't think it is the right one? There seems to be a second JSON attribute `version` which has a different number to the one I think it should have.

**Comment by wu-lee** [comment]
Ok, on second look it seems to be the right version on the ICA pop-up. Dean says the `version` attribute was added by a previous script he used to deploying it, so presumably won't generally be there.
