### ISSUE TITLE
update cache when linked data receives an update

### ISSUE THREAD

**Issue by dtmakm27** [SolidarityEconomyAssociation/sea-map#77]
look into creating a cronjob to check sea-map cache and synchronize with the data hosted on virtuoso

**Comment by wu-lee** [comment]
I would advise against a cronjob, assuming you mean that literally. This would require adding something to the server deployment to configure that job, which would be awkward for N arbitrary sea-map sites per server.

Mightn't it be simpler for the `get_dataset.php` script to:
- Check a timestamp for the cached data (either on the file's metadata, or in the file's internal data structure)
- If it is old enough, assume the cache has expired and re-get the data. This would be roughly equivalent to a cron-job with the same period as the expiry.

Alternatively, it might detect when to expire the cache from a timestamp obtained via 
- a HTTP HEAD request on the source URL for the HTTP data, or the meta.json file (assuming this static data is deployed at the same time as the Virtuoso data)
- or, via a special triple in the Virtuoso linked data.

(Which might work best depends on how long a full data query takes compared to HTTP HEADs or small SPARQL queries)

**Comment by wu-lee** [comment]
Here's another idea: don't do dynamic queries on Virtuoso from sea-map at all.  In practice, the query never changes.

Instead, add construction of the JSON data as an extra step in the open-data build process, by running the SPARQL query then. Store the result with the other static data.

The sea-map can then either HTTP get that data, optionally with caching based on the ETAG header (which would then be available).

This is more or less what the mutual-aid wiki people are (or might be) implementing for us for their dataset.

**Comment by dtmakm27** [comment]
> Instead, add construction of the JSON data as an extra step in the open-data build process, by running the SPARQL query then. Store the result with the other static data.

The sea-map can then either HTTP get that data, optionally with caching based on the ETAG header (which would then be available).



Don't think i get that :D , probably best to have a chat before i implement anything @wu-lee

**Comment by dtmakm27** [comment]
> I would advise against a cronjob, assuming you mean that literally. This would require adding something to the server deployment to configure that job, which would be awkward for N arbitrary sea-map sites per server.

Good idea

**Comment by dtmakm27** [comment]
@wu-lee try to curl this url https://dev.lod.coop/ica

Any idea why it might be giving me a 404? 
(when i specify the -L option for following redirects it doesn't seem to do anything as well)

**Comment by wu-lee** [comment]
> @wu-lee try to curl this url https://dev.lod.coop/ica
> 
> Any idea why it might be giving me a 404?
> (when i specify the -L option for following redirects it doesn't seem to do anything as well)

Short version: you need a trailing `/` - so https://dev.lod.coop/ica/

Longer version: there is something a bit weird going on since https://dev.lod.coop/ica works in a browser [edit: well, sometimes], but seems to get a 404 in `wget` / `curl`. 

IIRC I've tried to make sure that single-element paths with no trailing slash (like this one) get interpreted as needing redirection to index files rather than as initiative URIs.


Even longer version: With multi-element paths, e.g. https://dev.lod.coop/sea-lod/oxford, there's an unresolvable ambiguity. Is that an index or an initiative URI? Currently lack of a trailing slash means it's an initiative, a trailing slash an index (of initiatives). 

The LOD redirector doesn't have access to the data and so can't check to see what data files exist. It has to operate entirely by looking at the URI. So:

 - https://dev.lod.coop/sea-lod/oxford -> https://dev.data.solidarityeconomy.coop/sea-lod/oxford.html, which is a 404 because there is no initiative called `oxford` in the `sea-lod` namespace.
 - https://dev.lod.coop/sea-lod/oxford/ -> https://dev.data.solidarityeconomy.coop/sea-lod/oxford/index.html, an index of the initiatives in the `sea-lod/oxford` namespace.

And as a special case, because we don't put initiatives in the top-level namespace, I've tried to make sure the rule is:
 - https://dev.lod.coop/ica -> https://dev.lod.coop/ica/index.html

And not:
 - https://dev.lod.coop/ica -> https://dev.lod.coop/ica.html

**Comment by wu-lee** [comment]
> Don't think i get that :D , probably best to have a chat before i implement anything @wu-lee

Let me know when you can do that, ideally arrange a time via Discord.  I don't seem to be able to reach you.

**Comment by ColmMassey** [comment]
Noting that this is now urgent as it is hidding the autobuild processes on all our live and actively tested maps!

**Comment by ColmMassey** [comment]
Dotcoop is supposed to have been being updating bi-weekly for the last few months. Can either of you see how long it has been since the cache was updated? @dtmakm27 @wu-lee

**Comment by wu-lee** [comment]
Looks like the dotcoop data was last downloaded at 3am today (this is from dev-0):

```
  -rw-rw-r-- 1 seopendata seopendata 1263734 Oct 18 03:01 original.csv
  -rw-rw-r-- 1 seopendata seopendata      19 Oct 18 03:01 original.csv.etag
```

The dotcoop meta.json file in the data directory was generated shortly after the last data was downloaded:
```
  -rw-r--r-- 1 www-data www-data    279 Oct 18 03:12 meta.json
```

The cache on the dotcoop sea-map on dev-0 dates to last Thursday:
```
  -rw-rw-r-- 1 www-data www-data    4604 Sep 17 22:18 get_dataset.php
  -rw-r--r-- 1 www-data www-data 1974409 Oct 15 12:12 locCache.json
```

**Comment by dtmakm27** [comment]
@ColmMassey @wu-lee 
Implemented the auto-update feature. 
each time you load the map it makes a HEAD request to the url stored in default-graph-uri.txt and checks the latest modified time  (of the rdf files) then compares it with the previously stored time (from the previous request), then decides if the data is out of date. 

The only map updated with this currently is https://dev.dotcoop.solidarityeconomy.coop/
(I have tested it both locally and remotely) 

Shall we update the other maps?

**Comment by ColmMassey** [comment]
> Absolutely. Otherwise, as I understand correctly, the autobuild process for oxford, newbridge and mersey-green is incomplete.

And mutual aid.

**Comment by wu-lee** [comment]
As per https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/233#issuecomment-714544880, I've redeployed all the `dev-0` sea-maps with the latest sea-map code, which seems to do what it should.

**Comment by wu-lee** [comment]
Is it worth adding a feature request to make the sea-map caching optional? Presumably that's fairly easy, @dtmakm27 ?

**Comment by ColmMassey** [comment]
> Is it worth adding a feature request to make the sea-map caching optional? Presumably that's fairly easy, @dtmakm27 ?

I you agree @dtmakm27  can you create a ticket for this for the future?

**Comment by ColmMassey** [comment]
and I Think we can close it then.

**Comment by dtmakm27** [comment]
> Is it worth adding a feature request to make the sea-map caching optional? Presumably that's fairly easy, @dtmakm27 ?
> I you agree @dtmakm27 can you create a ticket for this for the future?





created here: https://github.com/SolidarityEconomyAssociation/sea-map/issues/79
