### ISSUE TITLE
Making caching optional for sea-map

### ISSUE THREAD

**Issue by dtmakm27** [SolidarityEconomyAssociation/sea-map#79]
Add a variable to enable/disable auto-caching feature, context:
https://github.com/SolidarityEconomyAssociation/sea-map/issues/77

**Comment by ColmMassey** [comment]
I believe we have addressed the issue prompting this. So no longer pressing.

**Comment by ColmMassey** [comment]
> I believe we have addressed the issue prompting this. So no longer pressing.

If we do this now we can postpone dealing with multi graph cacheing feature til later.

Was it @wu-lee or @dtmakm27 who was doing this?

**Comment by ColmMassey** [comment]
Can you take responsibility for this @wu-lee ?

**Comment by wu-lee** [comment]
Okay then

**Comment by dtmakm27** [comment]
Pushed to the latest sea-map (v0.1.63)

when the 
  "useCache": false
Variable is set to false in the config file, the php script will not cache the data (i.e. will directly request the data from Virtuoso every time)

**Comment by ColmMassey** [comment]
We need to test this on the https://dev.newbridge.solidarityeconomy.coop/

**Comment by wu-lee** [comment]
@dtmakm27 - what happens if that `useCache` config param is absent, or null? (As it will be for most sea-map deployments.) Will that disable caching when it shouldn't be?

**Comment by ColmMassey** [comment]
What should that behaviour be? 
useCache config param is absent, or null -> caching enabled - we don't need to change any other map config files
useCache config param is absent, or null -> caching disabled - seems more correct but we need to change all other map config files

**Comment by wu-lee** [comment]
I think the default case will be the latter, in which case we need to be aware. But what could work better would be to flip the logic, so it's `disableCache`, and the default will be false (so it's enabled by default, which keeps things consistent)

**Comment by ColmMassey** [comment]
> so it's `disableCache`,

Sounds sensible, and perhaps make the name more obvious, given the multiple types of caching we deal with. Would `disableLinkedDataCache` work?

**Comment by wu-lee** [comment]
I've started working on inverting the logic, and on close inspection the caching is actually not working at all currently. The browser-side code sends a parameter `useCache`,

https://github.com/SolidarityEconomyAssociation/sea-map/blob/ee1d90cb4ffb94d5fdad34e8860b4970e3b2cf45/www/map-app/app/model/sse_initiative.js#L627

whereas the server-side PHP code expects `use_cache`:

https://github.com/SolidarityEconomyAssociation/sea-map/blob/ee1d90cb4ffb94d5fdad34e8860b4970e3b2cf45/www/services/get_dataset.php#L164

Consequentially I think caching is always disabled in the latest code (this was added Dec 17th). 

This does mean caching is disabled, which ticks the box for Newbridge/Deep Adaptation (so it can use multiple data sets trivially by not trying to cache). However, I think I need to do a more detailed review of how the code works and maybe add some tests to finish this and avoid future regressions, as well as to see how to implement caching for multiple data sets.

I think this means I should move on to the Newbridge issues and return to this later, right?

**Comment by ColmMassey** [comment]
>  the caching is actually not working at all currently.

What about for DotCoop? Is the cache not working for it?

**Comment by wu-lee** [comment]
It's not working for anything using latest sea-map, no

**Comment by wu-lee** [comment]
But now it is (and on prod.dotcoop, not dev.dotcoop yet)

**Comment by ColmMassey** [comment]
Can we close it?

**Comment by wu-lee** [comment]
Well, I've patched one obvious bug, but the flag's logic is not yet reversed (`useCache` -> `disableLodCache`), and it doesn't seem well tested (or at all?)

As such I think it creates a problem for other sites without the reversed logic, and if time permits, it deserves a code review and some tests/testing.

But maybe not immediately?

**Comment by ColmMassey** [comment]
Let's test on Newbridge, as that's what's up next.

**Comment by ColmMassey** [comment]
This is not one I can test, so close if/when you feel it is done.
