### ISSUE TITLE
onMarkersNeedToShowLatestSelection needs to be fixed

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#8]

**Comment by dtmakm27** [comment]
This should be done in https://dev.playground.solidarityeconomy.coop/ @ColmMassey

**Comment by ColmMassey** [comment]
@dtmakm27 What was this issue?

**Comment by dtmakm27** [comment]
Small pop-up with the information about the initiative (name,address,www,etc..) did not pop up when clicking on the panel (now it does)
