### ISSUE TITLE
Replace RequireJS with Webpack

### ISSUE THREAD

**Issue by wu-lee** [SolidarityEconomyAssociation/sea-map#84]
RequireJS is rather outdated now, and doesn't play nicely with the NPM/NodeJS ecosystem of packages and code, which uses CommonJS modules rather than AMD modules (which RequireJS uses).

Doing this will make it simpler to upgrade packages using npm, simpler to debug, allow versioned javascript files (which helps avoid caching problems), and make it simpler for others to use and modify sea-map as a component.

**Comment by ColmMassey** [comment]
How far did you get with this @wu-lee Nick?

**Comment by wu-lee** [comment]
This has been done some time ago, so can be closed.

**Comment by ColmMassey** [comment]
Thought so
