### ISSUE TITLE
Implment advanced search panel

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#91]
See 

https://github.com/SolidarityEconomyAssociation/ica-project/issues/7

for designs
Requires the following
 - [x] https://github.com/SolidarityEconomyAssociation/open-data/issues/66
 - [x] https://github.com/SolidarityEconomyAssociation/open-data/issues/67

**Comment by ColmMassey** [comment]
Check this Issue, as it may suggests some changes required to the url search parameters required as we upgrade the use of filters with search. https://github.com/SolidarityEconomyAssociation/sea-map/issues/87

**Comment by ColmMassey** [comment]
ICA have indicated which panle display options they want.

[Web.1280.1_LL.pdf](https://github.com/SolidarityEconomyAssociation/sea-map/files/5882201/Web.1280.1_LL.pdf)

I think you can get the relevant assets from Melissa.

**Comment by King-Mob** [comment]
![sea - advanced search](https://user-images.githubusercontent.com/38507954/107256912-046b9300-6a32-11eb-8dda-7d42bece1854.png)
This is where I'm up to so far. The AND logic functions, the dropdowns display active filters, the dropdown is styled, changing option triggers a search.

There's 3 things left before I think it fits the spec.
* bug: initiatives on the map aren't the same thing as in the sidebar sometimes
* bug: back and forward act weird with the filtering sometimes
* populating dropdowns dynamically from the data

The first 2 might be done by tomorrow. The third one links with the discussion about doing SPARQL queries in js or using the sausage machine for indexing datasets that we didn't finish last week.

**Comment by ColmMassey** [comment]
Looking good. Can you move the Clear Filters button to above the list of initiatives?

>The third one links with the discussion about doing SPARQL queries in js  

See https://github.com/SolidarityEconomyAssociation/open-data/issues/66#issuecomment-775501513

**Comment by ColmMassey** [comment]
Buglets:
 - [ ] If I have a country selected and I then open the search panel, I think the country should be preselected in the Country dropdown.
 - [ ] The countries should be sorted alphabetically in the drop down.
 - [ ] The markers on the map don't always refresh as you might expect when moving backwards through search history. E.g. Without any filters go directly to search for _apple_. It produces no results. Shorten to _app_ and search, we get one result, _Fédération des Coopératives.._.If we return to the original search, the lone marker disappears, correctly. But going forward _Fédération des Coopérative.._ reappears in the search results, but the marker doesn't reappear on the map. If you hit enter, the search is repeated and the marker no appears correctly.

**Comment by King-Mob** [comment]
The two points on countries I think I can do by the end of work tomorrow. Bug with history and markers I'm less certain of, but I would expect a day or two.
