### ISSUE TITLE
Move blue tab to sit on panel on narrow screens

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#92]
The blue tab gets hidden on narrow screen. Move to sit on the panel below the other icons on narrow screens.

![Untitled](https://user-images.githubusercontent.com/1162642/103021451-0b058000-4542-11eb-888b-2872ac48575d.png)

**Comment by ColmMassey** [comment]
This feels like it should be trivial? Can you take a look @wu-lee

**Comment by wu-lee** [comment]
Hmm, isn't that tab the only thing which shows when the side-bar is hidden? If it's on the side-bar, it'll get hidden with the side bar.

**Comment by ColmMassey** [comment]
So it can't be permenantly there, but move between current and new position. Hmm.

**Comment by ColmMassey** [comment]
How about the simpler solution of reducing the width of the panel?

**Comment by ColmMassey** [comment]
Not doing this.
