### ISSUE TITLE
Timeout when loading multiple datasets and one of them fails to load

### ISSUE THREAD

**Issue by dtmakm27** [SolidarityEconomyAssociation/sea-map#94]
As per https://github.com/SolidarityEconomyAssociation/sea-map/issues/90  - multiple datasets can be loaded correctly, simultaneously. The map will wait for all datasets to load before displaying the map application. 

What should be added is a timeout functionality to stop waiting for a dataset to load after a certain amount of time.  

Check out how this starts the dataset loading 

https://github.com/SolidarityEconomyAssociation/sea-map/blob/f3e4badf394084e9996026f70649f8350aca8b72/www/map-app/app/model/sse_initiative.js#L633-L635

and I would suggest to start a timeout counter on a separate "thread" that counts down and calls the below event:
https://github.com/SolidarityEconomyAssociation/sea-map/blob/f3e4badf394084e9996026f70649f8350aca8b72/www/map-app/app/model/sse_initiative.js#L653

**Comment by ColmMassey** [comment]
Did this get done in the other work on this bug?

**Comment by ColmMassey** [comment]
Is this still an issue. Multi-source maps seem to be working again.

**Comment by ColmMassey** [comment]
Can you close this @wu-lee if you agree it is obsolete?

**Comment by wu-lee** [comment]
I think we can close this yes, any problems we notice can go in new issues.
