### ISSUE TITLE
Clear Filter disappearing

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#95]
The Clear Filter button should be black on whitet text, as in Melissa's design.

https://xd.adobe.com/view/6461afa1-69f1-496f-8085-475b24888a5c-3132/screen/895f3629-2bdf-48e5-92be-de3a6110d1f5?fullscreen&hints=on

Also I have noticed that the Clear Filter button seems to disappear when you use the back button to return to a local search.

T

**Comment by ColmMassey** [comment]
"[18:25, 12/01/2021] John Code-Op: I only have the clear filter button disappear after i've clicked clear and then gone back
[18:26, 12/01/2021] John Code-Op: is the desired behaviour to have the button reappear when going back? And on clicking it you are returned an unfiltered set of results for that search?

**Comment by ColmMassey** [comment]
It is a little subtle. I think there may be something else going on to do with how the arrow buttons are interpreted.

**Comment by ColmMassey** [comment]
If there is a filter still on the data, then the Clear Filter button still needs to be active.

Starting with a fresh instance of https://dev.dotcoop.solidarityeconomy.coop/
|  ACTION  |  RESULT  |
|---|---|
| 1) Select Canada in directory.  |  Black panel opens out to the right as expected |
| 2) Open Search panel  |   Black panel closes. Search panel appears with empty search in Canada. Clear Filter Button present |
| 3) Search for the string 'ca' | Plenty of hits. Scrolling down to bottom we can see the Clear Filter Button |
| 4) Click the Forward Arrow icon to get a fresh search.| Search box is empty. Clear Filter button still present as still got Canada filter on. |
| 5) Search for the string 'sa' |  Fewer hits, but scrolling down to bottom we can still see the Clear Filter Button |
| 6) Click the Clear Filters button | Many more hits now as expected . Clear Filter Button gone, as expected. |
| 7) Click the Backward Arrow icon.  | It looks like the Canada filter is back on and sa is in text box. But no Clear Filter button. |

**Comment by ColmMassey** [comment]
I think that we are in a halfway house between having the text search action as something which generates a new block on the stack and having adding and removing a filter as also creating a block on the stack.

**Comment by ColmMassey** [comment]
For the present, I don't mind which it is. Just needs to be consistent. If you agree with my interpretation, do what is easiest to make it consistent and for there to always be a Clear Filter option when the filter is on. (We can review when we implement the more complete filter options. https://github.com/SolidarityEconomyAssociation/sea-map/issues/91)

**Comment by King-Mob** [comment]
Ok so I think what I'm getting from this is clear filter needs to always be an option when viewing the results of a filtered search, and clicking it adds a block on the stack.
If we act the same as the back and forward buttons on the web browser, then the search initiated by clear filter replaces what was the forward parts of the stack.
I think this should make sense to people.

**Comment by ColmMassey** [comment]
> Ok so I think what I'm getting from this is clear filter needs to always be an option when viewing the results of a filtered search, and clicking it adds a block on the stack.

I think that should work.

**Comment by ColmMassey** [comment]
> If we act the same as the back and forward buttons on the web browser, then the search initiated by clear filter replaces what was the forward parts of the stack.
> I think this should make sense to people.

I agree. Editing the search parameters of a search halfway down the stack could cause confusion.

**Comment by ColmMassey** [comment]
> I agree. Editing the search parameters of a search halfway down the stack could cause confusion.

I can imagine some nice designs for an advanced search stack, where you can edit mid stack searches and still keep later searches, but probably only worth it when the searches are more complex and you want to keep the search history between sessions. We'd also need some more visual clues as to where in the stack you were, etc. (For the future, advanced R&D tool version...)
