### ISSUE TITLE
Dynamic resizing of dialog on large screens

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#99]
Set min and max heights for a dialog, but dynamically resize to visualise as much as possible within those bounds.

**Comment by King-Mob** [comment]
@ColmMassey there are some max heights and widths set already in the source code.

currently the size seems to be based partly on the content of the dialog, and partly on the min and max sizes set in the css.

So, for the same size of screen, dialogs can be different sizes based on the content.

I'm assuming that we want dialogs to be pretty much the same size for a given screen size.

**Comment by ColmMassey** [comment]
> I'm assuming that we want dialogs to be pretty much the same size for a given screen size.

I am not sure. Happy for you to suggest a way forward. What logic is followed to define ration of left to right parts of dialog? Probably worth identifying the ugliest layouts you have noticed as references.

**Comment by King-Mob** [comment]
I'm going to aim for a uniform ratio for all the marker dialogs and see what happens from that.

**Comment by King-Mob** [comment]
I've gone for a height of 300px and a width of 50vw, meaning percentage of viewport width.

**Comment by ColmMassey** [comment]
Where can I test this out?

**Comment by King-Mob** [comment]
@ColmMassey deployed to https://dev.ica.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
Did you have a list of the range of co-ops that you tested against?

**Comment by ColmMassey** [comment]
The scroll bar cannot be grabbed.

**Comment by ColmMassey** [comment]
> The scroll bar cannot be grabbed.

This is on smaller screen. Also on phones the scroll doesn't work at all.

**Comment by ColmMassey** [comment]
Smaller landscape screen options the dialog is off the screen.

**Comment by King-Mob** [comment]
@ColmMassey I haven't been able to replicate the scroll bar issue, could you let me know how to do that? It seems to function as normal on the mobile options on my browser.

With the smaller landscape issue, there's a couple of things we could do.

When markers are clicked on, they're centered on the screen. Could make it so that on small screens they're placed at bottom-centre? For the Pixel 2 XL and the iphone X, this just about fits on screen at 300px tall.

Could also make them a dynamic height on a smaller screen, something like, if the screen is smaller than 500px, make the dialogue 80% of the screen height?

**Comment by ColmMassey** [comment]
> @ColmMassey I haven't been able to replicate the scroll bar issue, could you let me know how to do that? It seems to function as normal on the mobile options on my browser.

Doesn't work on either my personal Fairfone or the work Huawei on Firefox. Also using Firfox response mode on window 10 desktop.

**Comment by King-Mob** [comment]
ok, I'll take a look on firefox

**Comment by ColmMassey** [comment]
> ok, I'll take a look on firefox

I am seeing it in Chrome too.

**Comment by King-Mob** [comment]
The panel on the small screen doesn't scroll.

**Comment by King-Mob** [comment]
Pan to center of dialogues rather than markers.
Move website to the left hand side of the dialogue.

**Comment by King-Mob** [comment]
Resolved the above, deployed to dev on ICA here: https://dev.ica.solidarityeconomy.coop/

The panning now only changes the vertical if the dialogue wouldn't be visible.

**Comment by ColmMassey** [comment]
Can you detect when part of the dialog is being hidden offscreen and how much of it? Is there a option to position the dialog to the left or right of the marker? I found this. 
https://gis.stackexchange.com/questions/194004/changing-popup-position-on-leaflet-marker

**Comment by ColmMassey** [comment]
Can the ratios of dialog be made configurable, as what looks good when the data set is rich looks way too big when the data sets are sparse?

**Comment by King-Mob** [comment]
see if we can create method for Colm to experiment with dialogue ratios, probably the url arguments

**Comment by King-Mob** [comment]
here's the way to format the url argument:

`/?dialogueSize={"width":"50vw!important","height":"300px","descriptionRatio":3}`

the quotes are important

**Comment by ColmMassey** [comment]
What does the word 'important' do in the arguemnt?

Where is the documentation entry? Should it be here https://github.com/SolidarityEconomyAssociation/sea-map/blob/master/CONFIG.md

**Comment by ColmMassey** [comment]
Should this work on current https://dev.ica.solidarityeconomy.coop/ ?   1.0.0_3971c80-dev

**Comment by King-Mob** [comment]
Because of the change-over to dev-1, I need to change my set up, but yes, should be there soon.

important is part of the css, i'll change that so it's automatically added.

I'll try to run the documentation generator too.

**Comment by ColmMassey** [comment]
>but yes, should be there soon.
Should it be up now?

**Comment by ColmMassey** [comment]
>Can you detect when part of the dialog is being hidden offscreen and how much of it? Is there a option to position the dialog to the left or right of the marker? I found this.
https://gis.stackexchange.com/questions/194004/changing-popup-position-on-leaflet-marker

I am closing the issue but was wondering if you did take a look at the popup position suggestion above. It would warrant a new ticket if we wanted to do it.

**Comment by King-Mob** [comment]
@ColmMassey I looked at it, it's similar to something we did on the council stuff for RBKC so definitely possible. Looks like you have to create the option yourself, as in there's not a built in method for it from leaflet.

I'm already detecting the edge of the screen to pan down if the marker is too high. I think the more time-consuming part would be writing the alternate styles for the pop-up, which shouldn't be too complicated.
